import Header from "@components/Header";
import Background from "@components/Background";
import PortfolioCard from "@components/PortfolioCard";
import StyledDiv from "@components/StyledDiv";
import Experience from "@components/Experience";
import Projects from "@components/Projects";
import Head from "next/head";
import { useState } from "react";
import ContactForm from "@components/ContactForm";
import ClickAwayListener from "react-advanced-click-away";

// const ScrollContainer = styled.div`
//   height: 100vh;
//   overflow-y: scroll;
//   scroll-snap-type: y mandatory
// `;

export default function HomePage() {
  const [showForm, setShowForm] = useState(false);
  return (
    <div>
      <Head>
        <title>Sanchit | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Background />
      <StyledDiv $position={"relative"} $padding={"1rem"} $height={"25%"}>
        <Header
          onClick={() => {
            if (!showForm) setShowForm(true);
          }}
        />
        {showForm && (
          <ClickAwayListener onClickAway={() => setShowForm(false)}>
            <StyledDiv
              $position={"absolute"}
              $zIndex={9999}
              $top={"90%"}
              $left={"55%"}
              $minWidth={"40%"}
            >
              <ContactForm />
            </StyledDiv>
          </ClickAwayListener>
        )}
      </StyledDiv>
      {/* <ScrollContainer> */}
      <StyledDiv
        $height={"98vh"}
        $width={"98.5vw"}
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <PortfolioCard />
      </StyledDiv>

      <StyledDiv
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <Experience />
      </StyledDiv>

      <StyledDiv
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <Projects />
      </StyledDiv>

      {/* </ScrollContainer> */}
    </div>
  );
}
