import Header from "@components/Header";
import Background from "@components/Background";
import PortfolioCard from "@components/PortfolioCard";
import StyledDiv from "@components/StyledDiv";
import Experience from "@components/Experience";
import Projects from "@components/Projects";
import Head from "next/head";
import { useState } from "react";
import ContactForm from "@components/ContactForm";
import ClickAwayListener from "react-advanced-click-away";
import StyledText from "@components/StyledText";
import { useTheme } from "styled-components";

// const ScrollContainer = styled.div`
//   height: 100vh;
//   overflow-y: scroll;
//   scroll-snap-type: y mandatory
// `;

export default function HomePage() {
  const [showForm, setShowForm] = useState(false);
  const theme = useTheme();

  return (
    <div>
      <Head>
        <title>Sanchit | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Background />
      <Header
        onClick={() => {
          if (!showForm) setShowForm(true);
        }}
      />
      {showForm && (
        <ClickAwayListener onClickAway={() => setShowForm(false)}>
          <StyledDiv
            $position={"absolute"}
            $zIndex={9999}
            $top={"90%"}
            $left={"55%"}
            $minWidth={"40%"}
          >
            <ContactForm />
          </StyledDiv>
        </ClickAwayListener>
      )}
      {/* <ScrollContainer> */}
      <StyledDiv
        $height={"98vh"}
        $width={"98.5vw"}
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <PortfolioCard />
      </StyledDiv>

      <StyledDiv
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <Experience />
      </StyledDiv>

      <StyledDiv
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <Projects />
      </StyledDiv>

      <StyledDiv
        $padding={"1rem"}
        $display={"flex"}
        $justifyContent={"center"}
        $alignItems={"center"}
        $position={"relative"}
        $scrollSnapAllign={"start"}
      >
        <StyledText
          as="label"
          htmlFor="message"
          $display="block"
          $margin="0 0 0.5rem 0"
          $fontSize="1.3rem"
          $fontWeight="500"
          $color={theme.colors.white.default}
        >
          © 2025 SanchitArora. For the ❤️ of Development.
        </StyledText>
      </StyledDiv>

      {/* </ScrollContainer> */}
    </div>
  );
}
